# k8s/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  large_data: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    ... (add more text to make it large)
